[package]
name = "generate-voices"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
headless_chrome = "1.0.17"
scraper = "0.23.1"
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = [
    "full",
] }
